name: run automation

on:
  schedule:
    - cron: '0 */1 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v6.0.2

      - name: setup python
        uses: actions/setup-python@v6.2.0
        with: 
          python-version: '3.13.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute script
        env:
          GIST_API: ${{secrets.GIST_API}}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY}}

          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN}}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY}}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET}}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN}}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET}}
          TWITTER_CLIENT_SECRET_ID: ${{ secrets.TWITTER_CLIENT_SECRET_ID}}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET}}
        run: python main.py
